# -*- coding: utf-8 -*-
"""aula 3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgCmWofSK-FtZrJOjgn1xWtY_IWrMpoX
"""

1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

numero = 5
print(numero *4)

2 - Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.

nome = 'leandro'
sobrenome = "clemente"
print(nome , sobrenome)

3 - Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.

numero1 = 10
numero2 = 5
print (numero1 , numero2)

4 - Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.

linguagem = "PYTHON"
numero = 5
print(linguagem , numero)

5 - Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

frase = (aula de python é?)
print(frase)

palavra = input(escreva uma palavra)
print (frase , palavra)

6 - Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".**

hora = '17'
minuto = '00'
segundos = '22'

print(hora+ ':', minutos+ ':'segundos)

7 - Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.

area = input("00")
numero = input ('0000')
numero2 = input ('0000')
print(area , numero , numero2)


8 - Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.

texto = "receita de pão "
texto1 = "Farinha"
texto2 = "1/2 copo de agua morna"
texto3 = "fermento biologico"
texto4 = "sal a gosto"

print(texto)
print(texto1, ",", texto2, ",", texto 3, ",", texto4)


 9 - Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.**

adjetivo1 = input (" digite um adjetivo: Triste ou feliz" )
adjetivo2 = input (" digite um adjetico: alegre ou triste" )
adjetivo3 = input (" digite um adjetivo: bem ou mal"  )



**1 - Crie uma condição para comparar idades: 45 e 18 -  QUAL É MENOR E QUAL É MAIOR?**






**2 - Crie um sistema para permitir a verificação de menores em um show**




**3 - Crie um algoritmo que permita a entrada de 3 notas de alunos, utilize o bloco de código if()****para verificar se o aluno passou.**